---
remote_backend:
  resource_group_name: # Name of the resource group where the storage account is located
  storage_account_name: # Name of the storage account
  container_name: # Name of the container
  key: # Unique key to identify the state file

general:
  environment: # Environment name

# --- Resource Group ---
resource_group:
  - name: # Name of the resource group
    location: # Location of the resource group
    tags: #Optional tags
      environment: "test"
      version: "1.0.0"
      createdBy: "TerraformCDK"
  - name: "group01"
    location: "northeurope"
    tags:
      environment: "test"
      owner: "John"
      organization: "finance"
  - name: "group02"
    location: "northeurope"
  # ...

# --- Virtual Networks ---
virtual_network:
  - name: # Name of the virtual network
    location: # Location of the virtual network
    resource_group_name: # Name of the resource group where the virtual network should go
    address_space: # Address space of the virtual network
  - name: "network01"
    location: "westeurope"
    resource_group_name: "rg-test-westeurope-group01"
    address_space: [ "10.101.0.0/16" ]
    dns_servers: [ "1.1.1.1" ] # Optional DNS servers
  - name: "network02"
    location: "northeurope"
    resource_group_name: "rg-test-northeurope-group01"
    address_space: [ "10.102.0.0/16", "10.103.0.0/16" ]
    subnets: # Optional subnets
      - name: "subnt01" # Name of the subnet
        address_space: [ "10.102.0.0/24" ] # Address space of the subnet
        delegation: # Optional delegation
          name: "Microsoft.Web/serverFarms"
          actions: [ "Microsoft.Network/virtualNetworks/subnets/join/action" ]

# --- Container Registry ---
container_registry:
  - name: # Name of the container registry (It will generate as cr<environment><name>)
    location: # Location of the container registry
    resource_group_name: # Name of the resource group where the container registry should go
    sku: # SKU of the container registry
    admin_enabled: # Admin enabled or not
  - name: "ourregistry01"
    location: "westeurope"
    resource_group_name: "rg-test-westeurope-group01"
    sku: "Standard"
    admin_enabled: True
  - name: "ourregistry02"
    location: "westeurope"
    resource_group_name: "rg-test-westeurope-group01"
    sku: "Standard"
    admin_enabled: True

app_service_plan:
  - name: # Name of the app service plan
    location: # Location of the app service plan (e.g. westeurope, northeurope, etc.)
    os_type: # OS type of the app service plan (e.g. Windows, Linux)
    sku_name: # SKU name of the app service plan (e.g. P1v3, P2v3, WS1, etc.)
    per_site_scaling_enabled: # Per site scaling enabled or not (True/False)
    worker_count: # Worker count
  - name: "l01"
    location: "northeurope"
    resource_group_name: "rg-test-westeurope-group01"
    os_type: "Linux"
    sku_name: "P1v3"
    per_site_scaling_enabled: True
    worker_count: 1
    certificates: # Optional certificates injected to the app service plan
      - key_vault_name: # Name of the key vault
        key_vault_resource_group_name: # Name of the resource group where the key vault is located
        key_vault_secret: # Name of the secret in the key vault (certificate)
  - name: "w01"
    location: "westeurope"
    resource_group_name: "rg-test-westeurope-group01"
    os_type: "Windows"
    sku_name: "P1v3"
    per_site_scaling_enabled: True
    worker_count: 1
    certificates:
      - key_vault_name: "mykeyvault"
        key_vault_resource_group_name: "mykeyvault-rg"
        key_vault_secret: "certificate01"

# --- Storage Account ---
storage_account:
  - name: # Name of the storage account (Maximum 22 characters)
    location: # Location of the storage account (e.g. westeurope)
    resource_group_name: # Name of the resource group
    account_tier: # Optional | Standard, Premium
    account_replication_type: # Optional | LRS, GRS, RAGRS, ZRS
    cross_tenant_replication_enabled: True
    access_tier: # Optional | Hot, Cool ...
    enable_https_traffic_only: # Optional | True, False
    min_tls_version: # Optional | TLS1_0, TLS1_1, TLS1_2
    allow_nested_items_to_be_public: # Optional | True, False
    shared_access_key_enabled: # Optional | True, False
    public_network_access_enabled: # Optional | True, False
    default_to_oauth_authentication: # Optional | True, False
    nfsv3_enabled: # Optional | True, False
    tags:
      environment: "test"
      version: "1.0.0"
      createdBy: "TerraformCDK"
